version: '3'

services:
  node:
    build: .
    container_name: node1
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mysql-db
    networks:
      - nodenet

  mysql-phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    networks:
      - nodenet
    depends_on:
      - mysql-db
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql

  mysql-db:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - nodenet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db

networks:
  nodenet:
    driver: bridge

volumes:
  mysql:
